# Copy to /etc/init/docker-dashd.conf
description "Docker container for dashd p2p node"
start on filesystem and started docker
stop on runlevel [!2345]
respawn
pre-start script
  # Clean-up if left behind
  docker rm -f dashd-node || true
  
  # Attempt to always update and fail silently if the network isn't ready
  docker pull dashpay/dashd || true
end script
script
  exec docker run --rm -v dashd-data:/dash --name=dashd-node --rm -p 9999:9999 -p 127.0.0.1:9998:9998 dashpay/dashd
end script
